name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install -r requirements.txt

    - name: 3. Move to Q3 directory
      run: |
        cd Q3/

    - name: 4. Ensure env.so is executable
      run: chmod +x eval.cpython-38-x86_64-linux-gnu.so

    - name: 5. Run Evaluation
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47
